disabled_rules:
- trailing_whitespace
- identifier_name
- xctfail_message
- unneeded_break_in_switch
- multiple_closures_with_trailing_closure
- force_try
identifier_name:
excluded:
- id

line_length: 200

function_body_length:
  warning: 45
  error: 100

function_parameter_count:
  warning: 5

cyclomatic_complexity:
  ignores_case_statements: true

type_name:
  allowed_symbols:
    - "_"
